# Generated by Django 5.1.3 on 2024-12-02 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='events',
            table='Events',
        ),
        migrations.AlterModelTable(
            name='locations',
            table='Locations',
        ),
        migrations.AlterModelTable(
            name='people',
            table='People',
        ),
        migrations.AlterModelTable(
            name='relationships',
            table='Relationships',
        ),
    ]
